baseURL = "http://jmewes.github.io/ep-gss-homepage"
title = "Google Smart Shopping powered by ePages"
defaultContentLanguageInSubdir = false
defaultContentLanguage = "en-us"

[languages]
  [languages.en-us]
  [languages.en]
  [languages.de]
    
